### ISSUE TITLE
It works well, but after a while it hangs/freezes.

### ISSUE THREAD

**Issue by vainiya** [esaracho/amuleweb-adaptable#1]
I use Amule with Docker, while the original theme doesn't cause it to hang, when I use your theme it works well for a few minutes and shortly after it stops responding...

**Comment by esaracho** [comment]
Hi, thanks for the report, I will be investigating.

**Comment by esaracho** [comment]
I performed a code cleanup, I have had only one crash so far and it is an amuled bug: https://github.com/amule-project/amule/issues/29
